"""Weather-dependent candidates for root crops and vegetables."""
from __future__ import annotations

from .types import BiologicalRiskCandidate, candidate

ROOT_VEGETABLE_CANDIDATES: tuple[BiologicalRiskCandidate, ...] = (
    candidate(
        "potato_early_blight_pdays",
        "Альтернариоз картофеля",
        "Alternaria solani",
        "disease",
        ("potato",),
        "legacy_model_review",
        ("температура воздуха", "накопление P-days"),
        ("дата появления всходов", "история поля", "восприимчивость сорта"),
        "Физиологическое окно восприимчивости и срок усиления обследований.",
        "NEWA Potato Diseases — P-days",
        ("https://newa.cornell.edu/potato-diseases",),
        "legacy_tool",
        "NEWA помечает модель картофеля как legacy. Перед локальной "
        "реализацией нужен полный алгоритм P-days и региональная проверка.",
    ),
    candidate(
        "potato_late_blight_blitecast",
        "Фитофтороз картофеля",
        "Phytophthora infestans",
        "disease",
        ("potato",),
        "legacy_model_review",
        ("температура", "относительная влажность", "осадки и увлажнение"),
        ("источник инокулюма", "фаза и сомкнутость ботвы", "региональные сообщения"),
        "Период благоприятной инфекции при подтверждённом риске заноса.",
        "NEWA Potato Diseases — Blitecast",
        (
            "https://newa.cornell.edu/potato-diseases",
            "https://www.gov.mb.ca/agriculture/crops/plant-diseases/"
            "late-blight-potatoes.html",
        ),
        "legacy_tool",
        "Погода без инокулюма не доказывает заражение. NEWA помечает "
        "инструмент как legacy; договор модели нужно воспроизвести отдельно.",
    ),
    candidate(
        "potato_tuberworm",
        "Картофельная моль",
        "Phthorimaea operculella",
        "pest",
        ("potato",),
        "published_contract",
        ("Tmin и Tmax воздуха", "градусо-сутки"),
        ("выбор одной опубликованной модели", "ловушки", "фаза и состояние клубней"),
        "Температурное развитие поколения после выбранной точки отсчёта.",
        "UC IPM Phenology Model Database",
        (
            "https://ipm.ucanr.edu/weather/phenology-models-description/"
            "potato-tuberworm/",
        ),
        "published_model",
        "Источник содержит несколько несовместимых нижних порогов и методов. "
        "В production нельзя смешивать их; сначала выбирается один договор.",
    ),
    candidate(
        "sugarbeet_cercospora_leaf_spot",
        "Церкоспороз сахарной свёклы",
        "Cercospora beticola",
        "disease",
        ("sugarbeet",),
        "operational_external_model",
        ("температура", "относительная влажность", "длительность увлажнения"),
        ("смыкание рядов", "источник инокулюма", "симптомы в районе или поле"),
        "Окно благоприятной инфекции и приоритет обследования.",
        "NDSU Cercospora Leaf Spot Guidance and NDAWN",
        (
            "https://www.ndsu.edu/agriculture/extension/publications/"
            "comparison-cercospora-and-bacterial-leaf-spots-sugarbeet",
            "https://www.ndsu.edu/agriculture/ag-hub/ag-topics/"
            "crop-production/crops/sugarbeets/cercospora-leaf-spot-sugarbeet",
        ),
        "current_guidance",
        "Источник указывает тёплую влажную погоду, высокую влажность и "
        "длительное увлажнение. Для production нужен точный договор NDAWN.",
    ),
    candidate(
        "sugarbeet_root_maggot",
        "Свекловичная корневая муха",
        "Tetanops myopaeformis",
        "pest",
        ("sugarbeet",),
        "operational_external_model",
        ("температурные накопления", "градусо-сутки"),
        ("региональная сеть наблюдений", "учёт лёта", "фаза культуры"),
        "Срок ожидаемой активности взрослых мух по внешней модели.",
        "NDAWN Sugar Beet Root Maggot Model",
        (
            "https://www.ag.ndsu.edu/news/newsreleases/2010/april-19-2010/"
            "ndawn-releases-sugar-beet-root-maggot-model/",
            "https://www.ndsu.edu/vpag/newsletter/"
            "ndsu_helping_control_sugarbeet_root_maggot",
        ),
        "current_operational_tool",
        "Модель построена по 15 годам наблюдений долины Ред-Ривер. Для другого "
        "региона нужны местная калибровка и данные фактического лёта.",
    ),
    candidate(
        "carrot_weevil",
        "Морковный долгоносик",
        "Listronotus oregonensis",
        "pest",
        ("carrot",),
        "published_contract",
        ("Tmin и Tmax воздуха", "градусо-сутки с базой 7 °C"),
        ("календарная точка отсчёта", "ловушки или осмотр", "фаза культуры"),
        "Окна весенней активности, яйцекладки и появления личинок.",
        "UC IPM Phenology Model Database",
        (
            "https://ipm.ucanr.edu/weather/phenology-models-description/"
            "carrot-weevil/",
        ),
        "published_model",
        "Модель проверялась в Огайо; сроки требуют местной проверки и "
        "подтверждения вредителя ловушками или осмотром.",
    ),
    candidate(
        "table_beet_cercospora_leaf_spot",
        "Церкоспороз столовой свёклы",
        "Cercospora beticola",
        "disease",
        ("beet",),
        "operational_external_model",
        ("температура", "относительная влажность", "увлажнение листьев"),
        ("дата посадки", "фаза культуры", "источник инокулюма"),
        "Риск инфекции за 2, 14, 21 день и сезон по внешней модели.",
        "NEWA Cercospora Leaf Spot of Table Beets",
        ("https://newa.cornell.edu/beet-cercospora-leaf-spot",),
        "current_operational_tool",
        "До локального расчёта нужен опубликованный алгоритм или официальный "
        "API NEWA; результат не доказывает наличие инфекции.",
    ),
    candidate(
        "tomato_disease_tomcast",
        "Комплекс листовых болезней томата TOMCAST",
        "Alternaria solani and other TOMCAST targets",
        "disease",
        ("tomato",),
        "legacy_model_review",
        ("температура", "длительность увлажнения листьев"),
        ("дата высадки", "фаза", "история поля", "симптомы"),
        "Накопление индексов благоприятности листовых инфекций.",
        "NEWA Tomato Diseases — TOMCAST",
        ("https://newa.cornell.edu/tomato-diseases",),
        "legacy_tool",
        "Инструмент NEWA помечен legacy; нужно точно зафиксировать перечень "
        "болезней, таблицу DSV и правила сброса накопления.",
    ),
    candidate(
        "tomato_late_blight_blitecast",
        "Фитофтороз томата",
        "Phytophthora infestans",
        "disease",
        ("tomato",),
        "legacy_model_review",
        ("температура", "высокая влажность", "осадки и увлажнение"),
        ("подтверждённый региональный очаг", "фаза", "осмотр растений"),
        "Период благоприятной инфекции после подтверждения риска заноса.",
        "NEWA Tomato Diseases — Blitecast",
        ("https://newa.cornell.edu/tomato-diseases",),
        "legacy_tool",
        "Погода не заменяет данные об очагах и переносе спор. Модель legacy "
        "нельзя включать без восстановления и проверки договора.",
    ),
    candidate(
        "tomato_pinworm",
        "Томатная минирующая моль",
        "Keiferia lycopersicella",
        "pest",
        ("tomato",),
        "published_contract",
        ("Tmin и Tmax воздуха", "нижний порог 10,2 °C", "верхний 35 °C"),
        ("ловушки или первое обнаружение", "фаза культуры", "учёт повреждений"),
        "Температурное развитие поколения и сроки обследования.",
        "UC IPM Phenology Model Database",
        (
            "https://ipm.ucanr.edu/weather/phenology-models-description/"
            "tomato-pinworm/",
        ),
        "published_model",
        "Модель не показывает численность и требует подтверждения ловушкой "
        "или полевым обнаружением.",
    ),
    candidate(
        "tomato_consperse_stink_bug",
        "Серый щитник",
        "Euschistus conspersus",
        "pest",
        ("tomato",),
        "published_contract",
        ("Tmin и Tmax воздуха", "нижний порог 12 °C", "градусо-сутки"),
        ("первая поимка в феромонной ловушке", "стряхивание и учёт нимф"),
        "Окно появления основной массы нимф после подтверждённой поимки.",
        "UC IPM Consperse Stink Bug Model",
        (
            "https://ipm.ucanr.edu/agriculture/tomato/consperse-stink-bug/",
        ),
        "current_guidance",
        "Точка отсчёта — реальная поимка. Решение зависит от полевого учёта, "
        "а не от одной суммы температур.",
    ),
    candidate(
        "cucurbit_downy_mildew",
        "Ложная мучнистая роса тыквенных",
        "Pseudoperonospora cubensis",
        "disease",
        ("cucumber", "zucchini", "watermelon", "melon"),
        "regional_signal_required",
        ("температура", "увлажнение листьев", "ветер", "осадки"),
        ("подтверждённый очаг", "траектория переноса спор", "восприимчивый хозяин"),
        "Погодное окно заноса и инфекции только после регионального сигнала.",
        "Cucurbit Downy Mildew IPM PIPE",
        ("https://cdm.ipmpipe.org/",),
        "suspended_service",
        "Сервис прогноза переноса был приостановлен. Без подтверждённого очага "
        "и переноса спор локальная погода недостаточна.",
    ),
    candidate(
        "cucurbit_powdery_mildew",
        "Мучнистая роса тыквенных",
        "Podosphaera xanthii and Golovinomyces cichoracearum",
        "disease",
        ("cucumber", "zucchini", "watermelon", "melon"),
        "weather_screening_only",
        ("температура", "влажность", "состояние полога"),
        ("восприимчивый сорт", "источник спор", "симптомы"),
        "Напоминание об обследовании при благоприятном погодном фоне.",
        "University of Minnesota Extension Cucurbit Diseases",
        (
            "https://extension.umn.edu/disease-management/"
            "powdery-mildew-cucurbits",
        ),
        "current_guidance",
        "Не найден открытый валидированный численный алгоритм для текущих "
        "культур и целевого региона.",
    ),
    candidate(
        "cucurbit_scab",
        "Парша тыквенных",
        "Cladosporium cucumerinum",
        "disease",
        ("cucumber", "zucchini", "melon"),
        "weather_screening_only",
        ("прохладная влажная погода", "осадки", "увлажнение листьев"),
        ("восприимчивый сорт", "заражённые остатки или семена", "симптомы"),
        "Напоминание об обследовании после прохладного влажного периода.",
        "University of Minnesota Extension Cucurbit Scab",
        ("https://extension.umn.edu/disease-management/cucurbit-scab",),
        "current_guidance",
        "Источник не связывает паршу с арбузом; поэтому арбуз в договор не "
        "добавлен автоматически.",
    ),
    candidate(
        "squash_bug_summer_squash",
        "Тыквенный клоп",
        "Anasa tristis",
        "pest",
        ("zucchini",),
        "published_contract",
        ("Tmin и Tmax воздуха", "нижний порог 14,46 °C", "верхний 33,33 °C"),
        ("тип культуры — летний кабачок", "полевой учёт яиц и нимф"),
        "Температурное развитие поколения на летнем кабачке.",
        "UC IPM Phenology Model Database",
        (
            "https://ipm.ucanr.edu/weather/phenology-models-description/"
            "squash-bug/",
        ),
        "published_model",
        "Параметры нельзя автоматически переносить на огурец, дыню или арбуз.",
    ),
    candidate(
        "onion_botrytis_leaf_blight",
        "Ботритиоз листьев лука",
        "Botrytis squamosa",
        "disease",
        ("onion",),
        "operational_external_model",
        ("температура", "увлажнение листьев", "осадки и влажность"),
        ("дата посадки", "фаза", "история поля", "симптомы"),
        "Потенциал инфекции по внешней модели.",
        "NEWA Onion Diseases",
        ("https://newa.cornell.edu/onion-diseases",),
        "current_operational_tool",
        "Нужен официальный алгоритм или API; модель не подтверждает заболевание.",
    ),
    candidate(
        "onion_downy_mildew",
        "Пероноспороз лука",
        "Peronospora destructor",
        "disease",
        ("onion",),
        "operational_external_model",
        ("температура", "относительная влажность", "увлажнение листьев"),
        ("дата посадки", "источник спор", "фаза", "симптомы"),
        "Потенциал инфекции по внешней модели.",
        "NEWA Onion Diseases",
        ("https://newa.cornell.edu/onion-diseases",),
        "current_operational_tool",
        "Источник спор и полевая проверка обязательны; локальная погода сама "
        "по себе не доказывает инфекцию.",
    ),
    candidate(
        "onion_purple_blotch",
        "Пурпурная пятнистость лука",
        "Alternaria porri",
        "disease",
        ("onion",),
        "operational_external_model",
        ("температура", "увлажнение листьев", "осадки и влажность"),
        ("дата посадки", "фаза", "история поля", "симптомы"),
        "Потенциал инфекции по внешней модели.",
        "NEWA Onion Diseases",
        ("https://newa.cornell.edu/onion-diseases",),
        "current_operational_tool",
        "Перед реализацией нужен воспроизводимый договор NEWA.",
    ),
    candidate(
        "onion_maggot",
        "Луковая муха",
        "Delia antiqua",
        "pest",
        ("onion",),
        "operational_external_model",
        ("Tmin и Tmax воздуха", "градусо-сутки base 40°F BE"),
        ("дата посадки", "ловушки", "история поля"),
        "Сроки лёта и критические окна по внешней модели.",
        "NEWA Onion Maggot",
        ("https://newa.cornell.edu/onion-maggot",),
        "current_operational_tool",
        "Пороги стадий необходимо извлечь из первичного договора NEWA; "
        "температура не заменяет ловушки.",
    ),
    candidate(
        "onion_thrips_green_onion",
        "Табачный трипс на зелёном луке",
        "Thrips tabaci",
        "pest",
        ("onion",),
        "published_contract",
        ("Tmin и Tmax воздуха", "нижний порог 11,5 °C", "градусо-сутки"),
        ("тип продукции — зелёный лук", "первое обнаружение", "учёт численности"),
        "Температурное развитие поколения после полевого обнаружения.",
        "UC IPM Phenology Model Database",
        (
            "https://ipm.ucanr.edu/weather/phenology-models-description/"
            "onion-thrips/",
        ),
        "published_model",
        "Источник относится к зелёному луку. Для репчатого лука требуется "
        "отдельная проверка, поэтому автоматическое включение запрещено.",
    ),
    candidate(
        "seedcorn_maggot_allium_after_tillage",
        "Ростковая муха после обработки почвы",
        "Delia platura",
        "pest",
        ("onion", "garlic"),
        "published_contract",
        ("Tmin и Tmax воздуха", "градусо-сутки с базой 3,9 °C"),
        ("дата обработки почвы или формирования гряд", "липкие ловушки", "осмотр"),
        "Окно появления первого поколения после подтверждённой обработки почвы.",
        "UC IPM Onion and Garlic Seedcorn Maggot Guidance",
        (
            "https://ipm.ucanr.edu/agriculture/onion-and-garlic/seedcorn-maggot/",
        ),
        "current_guidance",
        "Это отдельный договор и точка отсчёта; его нельзя смешивать с "
        "существующей моделью кукурузы и сои от 1 января.",
    ),
    candidate(
        "garlic_thrips_weather",
        "Трипсы чеснока",
        "Thrips tabaci and related thrips",
        "pest",
        ("garlic",),
        "weather_screening_only",
        ("жаркая сухая погода", "температура", "отсутствие дождя"),
        ("видовая идентификация", "учёт особей на растениях", "фаза"),
        "Напоминание об усилении полевого учёта в жаркую сухую погоду.",
        "UC IPM Onion and Garlic Thrips Guidance",
        ("https://ipm.ucanr.edu/agriculture/onion-and-garlic/thrips/",),
        "current_guidance",
        "Благоприятная погода не задаёт численность; модель зелёного лука "
        "не переносится на чеснок автоматически.",
    ),
)
